# Generated by Django 3.1.7 on 2021-03-28 15:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('title', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('posted_date', models.DateTimeField(default=datetime.datetime.now)),
                ('age', models.IntegerField(blank=True)),
                ('application', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Design', 'Design'), ('Business', 'Business'), ('Science', 'Science')], default=None, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
